springdoc:
  packagesToScan : com.greg
  pathsToMatch : /**
  swagger-ui:
    path: /swagger-ui.html

spring:
  cloud:
    config:
      enabled: false

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: metrics, info , health


