textdoubler:
  url: http://localhost:8090

springdoc:
  packagesToScan : com.greg
  pathsToMatch : /**
  swagger-ui:
    path: /swagger-ui.html

spring:
  cloud:
    config:
      enabled: false
server:
  port: 8081


feign:
  client:
    config:
      textdoubler:
        requestInterceptors:
          -  com.greg.microsrevice.caller.RequestLoggerInterceptor
